name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: secrete token
      run: echo ${{secrets.SANDESH}}
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: My first action
    - uses: actions/checkout@v1
      with:
        GITHUB_TOKEN: ${{secrets.SANDESH}}
      env:
        GITHUB_TOKEN: ${{secrets.SANDESH}}
      run: echo ${{secrets.SANDESH}}
    - name: Maven Deploy
      run: mvn deploy -Dregistry=https://maven.pkg.github.com/GaneshBabu-J -Dtoken=${{secrets.SANDESH}}
    
